language: node_js

node_js:
  - node

before_install:
  - sudo apt-get update
  - sudo apt-get install fakeroot jq -y
  - sudo apt-get install git-core -y
  - sudo apt-get install libavahi-compat-libdnssd-dev -y
  - sudo pip install awscli

install:

  - npm i -f
  - npm run build

script:
  - mkdir syncdist
  - mkdir syncdist/build
  - cp -R assets syncdist
  - cp dist/* syncdist/build
  - cp index.html syncdist
  - cd syncdist
  - aws s3 sync . s3://www.stylifier.com


env:
  global:
    - AWS_DEFAULT_REGION=eu-central-1
    - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - python
      - python-pip
